name: Generate Stats Card

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          theme: dark-github
          base: header, activity, community, repositories
          config_timezone: Asia/Seoul
